name: CPack

on:
    push:
     branches: [master]
    pull_request:
     branches: [master]
          
jobs: 
 build_Linux:   
  
  runs-on: ubuntu-latest

  steps: 
  - uses: actions/checkout@v3


  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest
  
  - name: Configurate
    run: |
        rm -rf ${{github.workspace}}/_build
        mkdir _build && cd _build
        cmake .. -DBUILD_TESTS=OFF
        cmake --build .
        cmake --build . --target package

  - name: Make a release
    uses: ncipollo/release-action@v1.10.0
    with:
      artifacts: "build/*.deb"
      token: ${{ secrets.GITHUB_TOKEN }}