name: CPack

on:
    workflow_dispatch:
    push:
      tags:
        - v*.*.*
          
jobs: 
 build_packages_Linux:   
  
  runs-on: ubuntu-latest

  permissions:
    contents: write


  steps: 
  - uses: actions/checkout@v3
  

  - name: Configurate
    run: |
        cd _build -D PRINT_VERSION=${GITHUB_REF_NAME#v}
        cmake --build .
        cmake --build . --target package
        cmake --build build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1.10.0
    with:
      artifacts: "build/*.deb"
      token: ${{ secrets.GITHUB_TOKEN }}
