name: CPack

on:
    push:
      branches: [master]
      tags:
        - v*.*.*
    pull_request:
      branches: [master]
          
jobs: 
 build_packages_Linux:   
  
  runs-on: ubuntu-latest

  permissions:
    contents: write

  steps: 
  - uses: actions/checkout@v3
  
  - name: Configurate
    run: |
        cmake ${{github.workspace}} -B ${{github.workspace}}/build -D PRINT_VERSION=${GITHUB_REF_NAME#v}
        cd _build
        cmake --build .
        cmake --build . --target package
        cmake --build build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1.10.0
    with:
      artifacts: "build/*.deb"
      token: ${{ secrets.GITHUB_TOKEN }}
