name: Actions

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest
  
  - name: Configurate
    run: |
      rm -rf ${{github.workspace}}/_build
      mkdir _build && cd _build
      cmake .. -DBUILD_TESTS=ON
      cmake --build .

  - name: my_exe
    run: ${{github.workspace}}/_build/my_exe

  - name: Run tests
    run: _build/my_test

  - name: package
    run: cmake --build ${{github.workspace}}/_build --target package

  - name: package_source
    run: cmake --build ${{github.workspace}}/_build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1
    with:
      artifacts: "_build/*.deb,_build/*.tar.gz,_build/*.zip"
      replaceArtifacts: false
      tag: 1.0.0
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
