name: Actions

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]
  
permissions:
  contents: write

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest
  
  - name: Configurate
    run: |
      rm -rf ${{github.workspace}}/_build
      mkdir _build && cd _build
      cmake .. -DBUILD_TESTS=ON
      cmake --build .

  - name: my_exe
    run: ${{github.workspace}}/_build/my_exe

  - name: Run tests
    run: _build/my_test

  - name: package
    run: cmake --build ${{github.workspace}}/_build --target package

  - name: package_source
    run: cmake --build ${{github.workspace}}/_build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1
    with:
      artifacts: "${{github.workspace}}/_build/*.deb,${{github.workspace}}/_build/*.tar.gz,${{github.workspace}}/_build/*.zip"
      tag: 1.0.0
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
  - name: qwe
    run: ls ${{github.workspace}}/_build/
  - name: Arts
    uses: actions/upload-artifact@v4
    with:
        name: Factory
        path: ${{github.workspace}}/_build/my_exe
