name: Actions

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest
  
  - name: Configurate
    run: |
      rm -rf ${{github.workspace}}/_build
      mkdir _build && cd _build
      cmake .. -DBUILD_TESTS=ON
      cmake --build .

  - name: my_exe
    run: ${{github.workspace}}/_build/my_exe

  - name: Run tests
    run: _build/my_test

  #- name: Make a release
    #uses: ncipollo/release-action@v1.10.0
    #with:
      #artifacts: "build/*.deb"
      #tag: 1.0.6
      #token: ${{ secrets.GITHUB_TOKEN }}
